// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace GrabadoBarralesWorkerService.Models.PgSql;

public partial class ESCORIALContext : DbContext
{
    public ESCORIALContext()
    {
    }

    public ESCORIALContext(DbContextOptions<ESCORIALContext> options)
        : base(options)
    {
    }

    public virtual DbSet<etiquetas_maestro_barrales> etiquetas_maestro_barrales { get; set; }
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .HasPostgresExtension("fuzzystrmatch")
            .HasPostgresExtension("hstore")
            .HasPostgresExtension("ltree")
            .HasPostgresExtension("pg_stat_statements")
            .HasPostgresExtension("pgstattuple")
            .HasPostgresExtension("unaccent");

        modelBuilder.Entity<etiquetas_maestro_barrales>(entity =>
        {
            entity.HasKey(e => e.id).HasName("etiquetas_maestro_barrales_pkey");

            entity.Property(e => e.id).HasDefaultValueSql("nextval('etiquetas_maestro_barrales_id_seq'::regclass)");
        });
        modelBuilder.HasSequence("aux_suceso_inc_seq");
        modelBuilder.HasSequence("hibernate_sequence", "web");

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}