// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GrabadoBarralesWorkerService.Models.MySql;

public partial class errores
{
    [Key]
    public int id { get; set; }

    [Column(TypeName = "text")]
    public string message { get; set; }

    [Column(TypeName = "text")]
    public string inner_exception { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha { get; set; }
    public int? puesto { get; set; }
}