// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Pomelo.EntityFrameworkCore.MySql.Scaffolding.Internal;

namespace GrabadoBarralesWorkerService.Models.MySql;

public partial class MySqlContext : DbContext
{
    public MySqlContext()
    {
    }

    public MySqlContext(DbContextOptions<MySqlContext> options)
        : base(options)
    {
    }

    public virtual DbSet<errores> errores { get; set; }

    public virtual DbSet<registros> registros { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        IConfiguration configuration = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory()) // Ruta al directorio del proyecto
            .AddJsonFile("appsettings.json") // Nombre del archivo de configuración
            .Build();

        var connectionString = configuration.GetConnectionString("MySql"); // Nombre de la cadena de conexión en appsettings.json

        if (!string.IsNullOrEmpty(connectionString))
        {
            optionsBuilder.UseMySql(connectionString, ServerVersion.Parse("8.0.40-mysql"));
        }
        else
        {
            // Manejo de error si la cadena de conexión no se encuentra en appsettings.json
            throw new Exception("No se encontró la cadena de conexión 'MySql' en appsettings.json");
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");

        modelBuilder.Entity<errores>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PRIMARY");

            entity.Property(e => e.fecha).HasDefaultValueSql("CURRENT_TIMESTAMP");
        });

        modelBuilder.Entity<registros>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PRIMARY");

            entity.Property(e => e.fecha).HasDefaultValueSql("CURRENT_TIMESTAMP");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}