// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GrabadoBarralesWorkerService.Models.MySql;

public partial class registros
{
    public int? tipo_barral { get; set; }

    public int? resultado { get; set; }

    public int? serie { get; set; }

    [StringLength(120)]
    public string operador { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha { get; set; }

    [Key]
    public int id { get; set; }
}